# Generated by Django 3.2.9 on 2021-11-15 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_number', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arm', models.CharField(max_length=10)),
                ('patient', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.patient')),
            ],
        ),
    ]
