# Generated by Django 3.2.9 on 2021-11-20 10:36

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_number', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('time', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('eligible', models.BooleanField(default=False)),
                ('inclusion', multiselectfield.db.fields.MultiSelectField(choices=[('in_epilepsy', 'Epilepsy dx'), ('in_freq_morethan_one', 'Freq > 1')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arm', models.CharField(max_length=10)),
                ('patient', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.patient')),
            ],
        ),
    ]
