# Generated by Django 3.2.9 on 2021-11-20 10:44

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='exclusion',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ex_medical_condition', '1) ผู้ป่วยที่มีระดับสติปัญญาบกพร่องรุนแรงหรือมีพัฒนาการช้า, ผู้ป่วยที่มีโรคทางจิตเวชรุนแรง (psychosis), PNES, ผู้ป่วยที่มีโรคประจำตัวรุนแรง (เช่นเนื้องอก, กระดูกหัก), ผู้ป่วยที่ไม่สามารถดูแลตนเองได้'), ('ex_not_android', '2) ไม่ได้ใช้ Android')], default=0, max_length=35),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='inclusion',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('in_epilepsy', '1)\tผู้ป่วยที่ได้รับการวินิจฉัยโรคลมชักและ/หรือญาติผู้ดูแลผู้ป่วยใกล้ชิด'), ('in_freq_morethan_one', '2) มีความถี่ในการชักมากกว่าหรือเท่ากับ 1 ครั้งต่อเดือนในช่วง 1 เดือนที่ผ่านมา'), ('in_age_morethan_eighteen', '3) อายุตั้งแต่ 18 ปีขึ้นไป')], max_length=57),
        ),
    ]
