# Generated by Django 3.2.9 on 2021-11-16 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_patient_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
