# Generated by Django 3.2.9 on 2022-03-01 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_alter_sequence_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='patient',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequence', to='registry.patient'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
