# Generated by Django 3.2.9 on 2021-11-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_auto_20211120_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='eligible',
            field=models.BooleanField(),
        ),
    ]
